# Docker compose file for production
services:
  # Nginx
  web:
    container_name: nginx
    image: nginx:1.27.1
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./php/index.php:/var/www/html/index.php # Pasar el archivo index.php a la ruta /
      - ./public/404.html:/var/www/html/404.html
    depends_on:
      - node

  node:
    container_name: nodejs
    build:
      context: .
      target: "prod"
    restart: always
    expose:
      - "3000"
    depends_on:
      - mongo

  # PHP
  php:
    container_name: php
    build:
      context: .
      target: "php-fpm"
    restart: always
    expose:
      - "9000"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - node

  # MongoDB
  mongo:
    container_name: mongodb
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db